// Code generated by protoc-gen-gogo.
// source: v1/quota/quota.proto
// DO NOT EDIT!

/*
Package mesos_v1_quota is a generated protocol buffer package.

It is generated from these files:
	v1/quota/quota.proto

It has these top-level messages:
	QuotaInfo
	QuotaRequest
	QuotaStatus
*/
package mesos_v1_quota

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import mesos_v1 "mesos/v1"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// TODO(joerg84): Add limits, i.e. upper bounds of resources that a
// role is allowed to use.
type QuotaInfo struct {
	// Quota is granted per role and not per framework, similar to
	// dynamic reservations.
	Role *string `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	// Principal which set the quota. Currently only operators can set quotas.
	Principal *string `protobuf:"bytes,2,opt,name=principal" json:"principal,omitempty"`
	// The guarantee that these resources are allocatable for the above role.
	// NOTE: `guarantee.role` should not specify any role except '*',
	// because quota does not reserve specific resources.
	Guarantee        []*mesos_v1.Resource `protobuf:"bytes,3,rep,name=guarantee" json:"guarantee,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *QuotaInfo) Reset()                    { *m = QuotaInfo{} }
func (m *QuotaInfo) String() string            { return proto.CompactTextString(m) }
func (*QuotaInfo) ProtoMessage()               {}
func (*QuotaInfo) Descriptor() ([]byte, []int) { return fileDescriptorQuota, []int{0} }

func (m *QuotaInfo) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

func (m *QuotaInfo) GetPrincipal() string {
	if m != nil && m.Principal != nil {
		return *m.Principal
	}
	return ""
}

func (m *QuotaInfo) GetGuarantee() []*mesos_v1.Resource {
	if m != nil {
		return m.Guarantee
	}
	return nil
}

// *
// `QuotaRequest` provides a schema for set quota JSON requests.
type QuotaRequest struct {
	// Disables the capacity heuristic check if set to `true`.
	Force *bool `protobuf:"varint,1,opt,name=force,def=0" json:"force,omitempty"`
	// The role for which to set quota.
	Role *string `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
	// The requested guarantee that these resources will be allocatable for
	// the above role.
	Guarantee        []*mesos_v1.Resource `protobuf:"bytes,3,rep,name=guarantee" json:"guarantee,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *QuotaRequest) Reset()                    { *m = QuotaRequest{} }
func (m *QuotaRequest) String() string            { return proto.CompactTextString(m) }
func (*QuotaRequest) ProtoMessage()               {}
func (*QuotaRequest) Descriptor() ([]byte, []int) { return fileDescriptorQuota, []int{1} }

const Default_QuotaRequest_Force bool = false

func (m *QuotaRequest) GetForce() bool {
	if m != nil && m.Force != nil {
		return *m.Force
	}
	return Default_QuotaRequest_Force
}

func (m *QuotaRequest) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

func (m *QuotaRequest) GetGuarantee() []*mesos_v1.Resource {
	if m != nil {
		return m.Guarantee
	}
	return nil
}

// *
// `QuotaStatus` describes the internal representation for the /quota/status
// response.
type QuotaStatus struct {
	// Quotas which are currently set, i.e. known to the master.
	Infos            []*QuotaInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *QuotaStatus) Reset()                    { *m = QuotaStatus{} }
func (m *QuotaStatus) String() string            { return proto.CompactTextString(m) }
func (*QuotaStatus) ProtoMessage()               {}
func (*QuotaStatus) Descriptor() ([]byte, []int) { return fileDescriptorQuota, []int{2} }

func (m *QuotaStatus) GetInfos() []*QuotaInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*QuotaInfo)(nil), "mesos.v1.quota.QuotaInfo")
	proto.RegisterType((*QuotaRequest)(nil), "mesos.v1.quota.QuotaRequest")
	proto.RegisterType((*QuotaStatus)(nil), "mesos.v1.quota.QuotaStatus")
}

func init() { proto.RegisterFile("v1/quota/quota.proto", fileDescriptorQuota) }

var fileDescriptorQuota = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x96, 0x20, 0x72, 0x45, 0x0c, 0x56, 0x87, 0x14, 0x18, 0xaa, 0xb2, 0x74, 0x72,
	0x08, 0x23, 0x03, 0x43, 0x37, 0x36, 0x30, 0xbf, 0xc0, 0x8a, 0x2e, 0x25, 0x52, 0xc8, 0x39, 0x3e,
	0x3b, 0xbf, 0x1f, 0xf5, 0x2c, 0xa5, 0xc0, 0xc6, 0x62, 0xd9, 0xef, 0x3d, 0xeb, 0x7b, 0x7a, 0xb0,
	0x9e, 0xea, 0x6a, 0x8c, 0x14, 0x6c, 0x3a, 0xb5, 0xf3, 0x14, 0x48, 0xdd, 0x7c, 0x21, 0x13, 0xeb,
	0xa9, 0xd6, 0xa2, 0xde, 0xae, 0xe5, 0x5d, 0x4d, 0x75, 0x95, 0x0c, 0x49, 0xed, 0x08, 0x8a, 0xf7,
	0x93, 0xfd, 0x3a, 0xb4, 0xa4, 0x14, 0x5c, 0x78, 0xea, 0xb1, 0xcc, 0xb6, 0xd9, 0xbe, 0x30, 0x72,
	0x57, 0xf7, 0x50, 0x38, 0xdf, 0x0d, 0x4d, 0xe7, 0x6c, 0x5f, 0x2e, 0xc4, 0x38, 0x0b, 0xea, 0x11,
	0x8a, 0x63, 0xb4, 0xde, 0x0e, 0x01, 0xb1, 0x5c, 0x6e, 0x97, 0xfb, 0xd5, 0x93, 0xd2, 0x33, 0xd8,
	0x20, 0x53, 0xf4, 0x0d, 0x9a, 0x73, 0x68, 0x37, 0xc2, 0xb5, 0x00, 0x0d, 0x8e, 0x11, 0x39, 0xa8,
	0x3b, 0xc8, 0x5b, 0xf2, 0x4d, 0x82, 0x5e, 0x3d, 0xe7, 0xad, 0xed, 0x19, 0x4d, 0xd2, 0xe6, 0x42,
	0x8b, 0x1f, 0x85, 0xfe, 0x8f, 0x7c, 0x81, 0x95, 0x20, 0x3f, 0x82, 0x0d, 0x91, 0x55, 0x05, 0x79,
	0x37, 0xb4, 0xc4, 0x65, 0x26, 0x9f, 0x37, 0xfa, 0xf7, 0x50, 0x7a, 0xde, 0xc3, 0xa4, 0xdc, 0xe1,
	0x01, 0x36, 0xe4, 0x8f, 0xda, 0x3a, 0xdb, 0x7c, 0xe2, 0x9f, 0xf4, 0xe1, 0xf2, 0xed, 0xb4, 0x23,
	0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x61, 0x60, 0x89, 0x85, 0x01, 0x00, 0x00,
}
